## Unit 2 - Linear Systems of Equations

### Linear Systems

A linear system of $m$ equations in $n$ uknowns has the forms:

$a_{11}x_1 + a_{12}x_2 + ... + a_{1n}x_n = b_{1}$\
$a_{21}x_1 + a_{22}x_2 + ... + a_{2n}x_n = b_{2}$\
$.$\
$.$\
$.$\
$a_{m1}x_1 + a_{m2}x_2 + ... + a_{mn}x_n = b_{m}$

$x$'s are unknowns, $a$'s and $b$ are known. There are $m$ equations.

Solving systems of these equations is the focus of this unit. 

This system can also be succinctly expressed as a matrix equation: \
$Ax = b$ \
where $A$ is the matrix of coefficients, $x$ is a vector of unknowns, $b$ is a vector of constants. More specifically:\
$A = [a_{ij}]_{i=1..m,j=1..n}$\
$x = [x_1, x_2, ... x_n]$\
$b = [b_1, b_2, ... b_m]$

We can also express this linear systems using an augmented matrix.\
$[A|b]$ (this is just shorthand that allows you to skip writing the $x$s)

Examples:

1) $x_1 + x_2 = 4$ \
   $x_1 - x_2 = 2$ 

2) $ \left[\begin{matrix} 1 & 1 \\ 1 & -1 \end{matrix}\right]
\left(\begin{matrix} x_1 \\ x_2 \end{matrix}\right)
=
\left(\begin{matrix} 4 \\ 2 \end{matrix}\right)
$ (This shows that the matrix-vector product of the coefficient matrix and the vector of unknowns gives the solution [[4],[2]] )

3) $ \left[\begin{matrix} 1 & 1 & | & 4 \\ 1 & -1 & | & 2 \end{matrix}\right]$

All three ways represent the same linear system.

### Types of Linear Systems

#### Underconstrained Linear System
$ \left[\begin{matrix}  &  &  &  & | \\  &  &  &  & | \end{matrix}\right]$

Typically the number of rows is less than the number of columns ($m<n$). There are an infinite number of solutions. There are many more variables than there are equations. 

Example:

$ \left[\begin{matrix} 1 & 2 & | & 3 \\ 0 & 0 & | & 0 \end{matrix}\right]$

$x_1 + 2x_2 = 3$\
$0x_1 + 0x_2 = 0$

There is an infinite number of solutions that can be expressed as \
$\left(\begin{matrix} x_1 \\ x_2 \end{matrix}\right)$ such that $x_1 + 2x_2 = 3$

An underconstrained system with $m<n$ can be augmented byy rows of 0's to make it square (perfect).

#### Perfectly Constrained
$ \left[\begin{matrix}  &  &  &  & | \\  &  &  &  & | \\  &  &  &  & |\end{matrix}\right]$

Typically, $m=n$. One unique solution.

Example:

$ \left[\begin{matrix} 1 & 0 & | & 3 \\ 0 & 2 & | & 0 \end{matrix}\right]$

$x_1 + 0x_2 = 3$\
$0x_1 + 2x_2 = 0$

There is a unique solution that can be expressed as \
$\left(\begin{matrix} x_1 \\ x_2 \end{matrix}\right)$ = $\left(\begin{matrix} 3 \\ 0 \end{matrix}\right)$

Our attention to linear systems will focus on Perfectly Constrained systems where $m=n$

#### Over Constrained
$ \left[\begin{matrix}  &  &  &  & | \\  &  &  &  & | \\  &  &  &  & | \\  &  &  &  & | \\  &  &  &  & | \end{matrix}\right]$

Typically, $m>n$. There is no solution.

Example:

$ \left[\begin{matrix} 1 & 0 & | & 3 \\ 2 & 0 & | & 0 \end{matrix}\right]$

$1x_1 + 0x_2 = 3$\
$2x_1 + 0x_2 = 0$

There is no solution since these equations are inconsistent.

$x_1 = 3$\
2x_1 = 0

This is a very common case in data science. Number of features is usually much less than data points so there's not exact solution. In this case you want to find some weighting of features that is a best fit. You can get a good approximate solution to over constrained systems by solving a related system with a square matrix.

### Solving Linear Systems by Direct Methods

Three operations on linear systems that do not change the solution

1) Multiply an equation by a non-zero constant
2) Exchange the order of two equations
3) Replace an equation with the sum of itself and a constant multiple of another equation

Example

$x_1 + x_2 = 4$\
$x_1 - x_2 = 2$

Same solution as the following equations:

By #1\
$2x_1 + 2x_2 = 8$ (multiplied this equation by 2)\
$x_1-x_2=2$

By #2 (just swap the order of the equations)\
$x_1 - x_2 = 2$\
$2x_1 + 2x_2 = 8$\

By #3\
$x_1 - x_2 = 2$\
$2x_1 + 2x_2 = 8 = eq_2 = eq_2 - 2eq_1$ (replace equation 2 with a constant multiple of another equation. in this case $eq_2 = eq_2 - 2eq_1$\
This gives the following new equations:\
$x_1 - x_2 = 2$\
$0 + 4x_2 = 4$

These operations don't need to be applied in order - this was just an example.

#### Elementary Row Operations on Augmented Matrices

1) $R_i \leftarrow cR_i$ (Replace $Row_i$ with a consant $c$ times $Row_i$)

2) $R_i \leftarrow\rightarrow R_j$ (Swap rows i and j)

3) $R_i \leftarrow R_i + aR_j$ (replace row i with row i + a time row j)

Example (same problem from above example)

$x_1 + x_2 = 4$\
$x_1 - x_2 = 2$

$ \left[\begin{matrix} 1 & 1 & | & 4 \\ 1 & -1 & | & 2 \end{matrix}\right] \rightarrow \left[\begin{matrix} 1 & 1 & | & 4 \\ 0 & -2 & | & -2 \end{matrix}\right]$

Using operation #3, we can replace the second equation with the sum of the equation and constant multiple of another equation (in this case, -1). Multiplying equation 1 by -1 gives $-x_1 - x_2 = - 4$. 

Then, $R_2 - R_1 = x_1 - x_1 -x_2 - x_2 = -4 + 2$

$R_2 \leftarrow R_2 - R_1$ (this is the notation used for the operation above. It means "replace row 2 with row 2 - row 1)

The second equation can now be rewritten as

$-2x_2 = -2 $ \
So $x_2 = 1$

Now, going back to the first equation:

$x_1 + 1 = 4$\
$x_1 = 3$

$\left(\begin{matrix} x_1 \\ x_2 \end{matrix}\right) = \left(\begin{matrix} 3 \\ 1\end{matrix}\right)$

Solving this system of equations amounts to finding the vector of unknowns such that the vector product of the given matrix and the vector of unknowns give ( [[4],[2]]). 

In [50]:
import numpy as np

# In python

given_matrix = [[1,1],[1,-1]]
matrix_of_unknowns = [[3],[1]]
solution = [[4],[2]]

result = np.dot(given_matrix, matrix_of_unknowns)  #matrix-vector product
print(result)
assert np.array_equal(result, solution)


[[4]
 [2]]


### Gaussian Elimination with Backward Substitution

Specific method that can be applied to a square coefficient matrix

Given an augmented matrix $[A,|b]$ with $A \in \mathbb{R}^{m*n}$

Step 1 (Gaussian Elimination) - Row reduce $[A|b]$ to get $[U|b']$ where $U$ is upper triangular with nonzero diagonal entries.

$U$ = 
$ \left[\begin{matrix} x & x & x & x \\ 0 & x & x & x \\ 0 & 0 & x & x \\ 0 & 0 & 0 & x \end{matrix}\right]$ = all the information in $U$ is in the upper right triangular area.

Step 2 (Backward Substitution) - Iteratively solve for $x$ in the order $x_x, x_{n-1}, ... x_1$

Example:

$ \left[\begin{matrix} 1 & 1 & 1 & | & 6 \\ -1 & 1 & 1 & | & 4 \\ 2 & -1 & 1 & | & 3\end{matrix}\right]$

**Step 1 Gaussian Elimination** - Turn the bottom left 3 entries into $0$s. "Use the top left element ($a_{11}$ - the very top left 1) as a pivot against row 2 and row 3. "

$Row_2 \leftarrow Row_2 + Row_1$ (Replace row2 with row2+row1)\
$Row_3 \leftarrow $Row_3 - 2*Row_1$ (Replace row3 with row3 - 2 times row1)

That gives:

$\left[\begin{matrix} 1 & 1 & 1 & | & 6 \\ 0 & 2 & 2 & | & 10 \\ 0 & -3 & -1 & | & -9\end{matrix}\right]$

Gaussian elimination always says to use the diagonal row as the pivot, so here we pivot on $Row_2$

$Row_3 \rightarrow Row_3 + 3/2*Row_2$

That gives:

$\left[\begin{matrix} 1 & 1 & 1 & | & 6 \\ 0 & 2 & 2 & | & 10 \\ 0 & 0 & 2 & | & 6\end{matrix}\right]$

That completes the Guassian Elimination piece.

**Step 2 Backward Substitution**: 

Solve for x_3 (the final row in the matrix): \
$2x_3 = 6$\
$x_3 = 3$

Solve for x_2:\
$2x_2 + 2x_3 = 10 $\
$2x_2 + 2*3 = 10$ (replace x_3 with 3 solved in the previous step)\
$2x_2 = 4$\
$x_2 = 2$

Solve for x_1:\
$x_1 + x_2 + x_3 = 6$\
$x_1 + 2 + 3 = 6$\
$x_1 = 1$

So, the solution vector is:

$\vec{x} = \left(\begin{matrix} x_1 \\ x_2 \\ x_3\end{matrix}\right)$ = $\left(\begin{matrix} 1 \\ 2 \\ 3\end{matrix}\right)$

The pseudocode for these algorithms is very simple. 

**Gaussian Elimination Algorithm**:

Input $[A|b]$, $A \in \mathbb{R}^{m*n}$, $b \in \mathbb{R}^n$\
Output $[U|b']$, $U \in \mathbb{R}^{m*n}$, $b' \in \mathbb{R}^n$ and $U$ is upper triangular: $U_{ij} = 0$ for $i > j$ and nondiagonal: $U_{jj} != 0$ for all $j$

For columns $j = 1$ to $n$:\
&nbsp;&nbsp;If $a_{jj} == 0$, Output FAIL\
&nbsp;&nbsp;For rows $i > j$\
&nbsp;&nbsp;&nbsp;&nbsp;$Row_i \rightarrow Row_i + (a_{ij} / a_{jj}) * Row_j$ (this says $a_{ij}$ divided by $a_{jj}$)\
&nbsp;&nbsp;Output Resulting $[U,b']$

**Backward Substituion Algorithm**:

Input $[U,b']$
Ouput $x \in \mathbb{R}^n$

For $i = n$ to $1$\
&nbsp;&nbsp;$x_i = (b_i - \sum_{j>i}^na_{ij}x_j) / a_{ii}$\
Output x

**Run Times:**

The Gaussian Elimination algorithm works in $n^3$ time\
The Backward Substitution algorithm works in $n^2$ time

Gaussian Elimination is very straightforward, but we e need faster, and possibly less straighforward, methods to solve this problem. 

In [171]:
import numpy as np

def gaussian_elimination(A):
    for j in range(len(A[0])):
        if A[j][j] == 0:
            return -1 # ERROR
        for i in range(j+1, len(A)):
            A[i] = np.add(A[i], np.multiply(-A[i][j] / A[j][j], A[j]))
            # in the above, the algorithm explained in the 
            # lecture did not include the negative in the -A[i][j]
            # but it seems to be right
    return A

A = [[ 1,  1, 1],
     [-1,  1, 1],
     [ 2, -1, 1]]
A_answer = [[1.,1.,1.],[0.,2.,2.],[0.,0.,2.]]

assert gaussian_elimination([[0,0,0],[0,0,0]]) == -1
assert np.array_equal(gaussian_elimination(A), A_answer)

print(f'Gaussian Elimination is {gaussian_elimination(A)}')

def backward_substitution(U, b_prime):
    x = [0 for i in range(len(U))]
    for i in range(len(U)-1,-1,-1):
        row_sum = 0
        for j in range(len(U[0])):
            row_sum = row_sum + U[i][j]*x[j]
        x[i] = (b_prime[i] - row_sum) / U[i][i]
    return x

b_prime = [6,10,6]
x_answer = [1.,2.,3.]

print(f'Backward Substitution is {backward_substitution(gaussian_elimination(A), b_prime)}')
assert np.array_equal(backward_substitution(gaussian_elimination(A), b_prime), x_answer)

Gaussian Elimination is [[1, 1, 1], array([0., 2., 2.]), array([0., 0., 2.])]
Backward Substitution is [1.0, 2.0, 3.0]


##### Elementary Matrices

The elementary row operations previously introduced that do not change the solution to a linear system can be accomplished by matrix multiplication.

**Type 1 Operations:** $Row_i \leftarrow cRow_i$


$\left[\begin{matrix} & & & &\\ x & x & x & x \\ & & & & \end{matrix}\right]$
$\rightarrow$ c
$\left[\begin{matrix} &  & & &\\ cx & cx & cx & cx \\ & & & & \end{matrix}\right]$

Take the $i$th row, and multiply the constant $c$ by the whole row.

We claim there's some elementary matrix that accomplishes the same thing as the row operation described above.

What is that matrix? It's this one:

Explanation: If the $c$ weren't in the leftmost matrix, it would just be the identity matrix and would just give the original matrix as the result. Having $c$ in the identity matrix will multiply $c$ against the $i$th row of the original matric (since $c$ is in the $i$th row).  

$\left[\begin{matrix} 1& 0 & 0  \\ 0 & c & 0  \\ 0 & 0 & 1 \end{matrix}\right]$
$\left[\begin{matrix} &  &  & &  \\ x & x & x & x \\  &  &  & & \end{matrix}\right]$
$\rightarrow$ c
$\left[\begin{matrix} &  &  & &  \\ x & x & x & x \\  &  &  & & \end{matrix}\right]$

**Type 2 Operations:** $Row_i \leftarrow\rightarrow Row_j$

Replace the $ii$th entry and the $jj$th entry with 0's and place a 1 in the $ij$th position and the $ji$th position.

$\left[\begin{matrix} 1 & 0 & 0 & 0 & 0 \\ 0 & 0 & 0 & 1 & 0  \\ 0 & 0 & 1 & 0 & 0 \\
0 & 1 & 0 & 0 & 0 \\ 0 & 0 & 0 & 0 & 1 \end{matrix}\right]$
$\left[\begin{matrix} & & & & & \\ i & i & i & i & i \\ & & & & & \\ j & j & j & j & j & \\ & & & & & \end{matrix}\right]$
$\rightarrow$
$\left[\begin{matrix} &  & & & &\\ j & j & j & j &j\\ & & & & &\\ i& i& i& i& i& \\ & & & & & \end{matrix}\right]$

**Type 3 Operations:** $Row_i \leftarrow Row_i + cRow_j$

Below, $c$ is in the $ij$th row ($i$ is rows, $j$ is columns). This has the effect of multiplying the $jth$ row by $c$ and placing that result in the $i$th row of the resulting matrix. 

$\left[\begin{matrix} 1 & 0 & 0 & 0 & 0 \\ 0 & 0 & 0 & 0 & 0  \\ 0 & 0 & 1 & 0 & 0 \\
0 & c & 0 & 0 & 0 \\ 0 & 0 & 0 & 0 & 1 \end{matrix}\right]$
$\left[\begin{matrix} & & & & & \\ i & i & i & i & i \\ & & & & & \\ j & j & j & j & j & \\ & & & & & \end{matrix}\right]$
$\rightarrow$
$\left[\begin{matrix} &  & & & &\\ cj & cj & cj & cj &cj\\ & & & & &\\ j& j& j& j& j& \\ & & & & & \end{matrix}\right]$

Examples:

$E_1$ = $\left[\begin{matrix} 1& 0 & 0  \\ 0 & 1 & 0  \\ 0 & 0 & 2 \end{matrix}\right]$ (Type 1 Elementary Matrix)

$E_2$ = $\left[\begin{matrix} 1& 0 & 0  \\ 0 & 0 & 1  \\ 0 & 1 & 0 \end{matrix}\right]$ (Type 2 Elementary Matrix)

$E_3$ = $\left[\begin{matrix} 1& 0 & 0  \\ 0 & 1 & 1  \\ 0 & 2 & 1 \end{matrix}\right]$
(Type 3 Elementary Matrix)

$A$ = $\left[\begin{matrix} 1& 2 & 3  \\ 4 & 5 & 6  \\ 7 &8 & 9 \end{matrix}\right]$ 

By Matrix Multiplication:

$E_1A$ = $\left[\begin{matrix} 1& 0 & 0  \\ 0 & 1 & 0  \\ 0 & 0 & 2 \end{matrix}\right]$ $\left[\begin{matrix} 1& 2 & 3  \\ 4 & 5 & 6  \\ 7 &8 & 9 \end{matrix}\right]$ = $\left[\begin{matrix} 1& 2 & 3  \\ 4 & 5 & 6  \\ 14 & 16 & 18 \end{matrix}\right]$ $Row_3 \leftarrow cRow_3$ where $c=2$

$E_2A$ = $\left[\begin{matrix} 1& 0 & 0  \\ 0 & 0 & 1  \\ 0 & 1 & 0 \end{matrix}\right]$ $\left[\begin{matrix} 1& 2 & 3  \\ 4 & 5 & 6  \\ 7 &8 & 9 \end{matrix}\right]$ = 
$\left[\begin{matrix} 1& 2 & 3  \\ 7 & 8 & 9  \\ 4 & 5 & 6 \end{matrix}\right]$ $Row_3 \leftarrow\rightarrow Row_2$

$E_3A$ = $\left[\begin{matrix} 1& 0 & 0  \\ 0 & 1 & 0  \\ 0 & 2 & 1 \end{matrix}\right]$ $\left[\begin{matrix} 1& 2 & 3  \\ 4 & 5 & 6  \\ 7 &8 & 9 \end{matrix}\right]$ = 
$\left[\begin{matrix} 1& 2 & 3  \\ 4 & 5 & 6  \\ 15 & 18 & 21 \end{matrix}\right]$ $Row_3 \leftarrow Row_3 + 2Row_2$

To undo and elementary operation:

$E_1$ = $\left[\begin{matrix} 1& 0 & 0  \\ 0 & 1 & 0  \\ 0 & 0 & 1/2 \end{matrix}\right]$

$E_2$ = $E_2$ (This will swap the rows back)

$E_3$ = $\left[\begin{matrix} 1& 0 & 0  \\ 0 & 1 & 0  \\ 0 & -2 & 1 \end{matrix}\right]$


In [71]:
import numpy as np

e_1 = [[1,0,0],[0,1,0],[0,0,2]]
e_2 = [[1,0,0],[0,0,1],[0,1,0]]
e_3 = [[1,0,0],[0,1,0],[0,2,1]]
A = [[1,2,3],[4,5,6],[7,8,9]]

e_1A = np.dot(e_1, A)
e_2A = np.dot(e_2, A)
e_3A = np.dot(e_3, A)

print(f'E_1A = \n {e_1A}\n')
print(f'E_2A = \n {e_2A}\n')
print(f'E_3A = \n {e_3A}\n')

# Undo the operations

e_1_undo = [[1,0,0],[0,1,0],[0,0,1/2]]
e_2_undo = e_2
e_3_undo = [[1,0,0],[0,1,0],[0,-2,1]]

e_1A_undo = np.dot(e_1_undo, e_1A)
e_2A_undo = np.dot(e_2_undo, e_2A)
e_3A_undo = np.dot(e_3_undo, e_3A)

print(f'E_1A_undo = \n {e_1A_undo}\n')
print(f'E_2A_undo = \n {e_2A_undo}\n')
print(f'E_3A_undo = \n {e_3A_undo}\n')


E_1A = 
 [[ 1  2  3]
 [ 4  5  6]
 [14 16 18]]

E_2A = 
 [[1 2 3]
 [7 8 9]
 [4 5 6]]

E_3A = 
 [[ 1  2  3]
 [ 4  5  6]
 [15 18 21]]

E_1A_undo = 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

E_2A_undo = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

E_3A_undo = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]



### LU Factorization

Alternative way to solve a linear system based on Guassian elimination but you don't have to worry about the vector of constants $b$ to solve. If you have a really ugly $b$, then you can use LU factorization to perform the operations just using the coefficient matrix. 

Theorem: If Gaussian Elimination succeeds in row-reducing $A$ to $U$ using only Type 3 operations, then $A$ has a factorization $A=LU$ where $L$ is unit lower triangular and $U$ is upper triangular with non-zero diagonal entries.

$L = $$\left[\begin{matrix} 1 & 0 & 0 & 0 & 0 \\ x & 1 & 0 & 0 & 0  \\ x & x & 1 & 0 & 0 \\
x &x & x & 1 & 0 \\ x & x & x & x & 1 \end{matrix}\right]$ (1's on the diagonal, non-zero entries in the lower half, zeros in the upper half)

$U = $$\left[\begin{matrix} x & x & x & x & x \\ 0 & x & x & x & x  \\ 0& 0 & x & x & x \\
0 &0 & 0 & x & x \\ 0 & 0 & 0 & 0 & x \end{matrix}\right]$ (0's on the lower half, non-zero entries in the upper diagonal and diagonal)

We will write $A$ as a product of $L$ and $U$. $U$ is the result of Guassian elimination. $L$ is equal to the matrix that undoes all the row operations ($L$ comes from looking at all the row operations that have been performed).

Not every matrix has an $LU$ factorization. 

Example:

Step 1: Use Gaussian elimination on coefficient matrix

$A = $$\left[\begin{matrix} 1 & 1 & 1 \\ -1 & 1 & 1 \\ 2 & -1 & 1 \\\end{matrix}\right]$ 

$Row_2 \leftarrow Row_2+Row_1$\
$Row_3 \leftarrow Row_3-2Row_1$

$A = $$\left[\begin{matrix} 1 & 1 & 1 \\ -1 & 1 & 1 \\ 2 & -1 & 1 \\\end{matrix}\right]$ 
$\rightarrow $$\left[\begin{matrix} 1 & 1 & 1 \\ 0 & 2 & 2 \\ 0 & -3 & -1 \\\end{matrix}\right]$

$Row_3 \leftarrow Row_3+(3/2)Row_1$\
$\left[\begin{matrix} 1 & 1 & 1 \\ 0 & 2 & 2 \\ 0 & -3 & -1 \\\end{matrix}\right]$$\rightarrow $$\left[\begin{matrix} 1 & 1 & 1 \\ 0 & 2 & 2 \\ 0 & 0 & 2 \\\end{matrix}\right] = U$

To get $L$, need to look at the row operations that have been performed:

$Row_2 \leftarrow Row_2+Row_1$\
$Row_3 \leftarrow Row_3-2Row_1$\
$Row_3 \leftarrow Row_3+(3/2)Row_1$

You look at what the multiplier was that was needed in order to zero out the coefficient and take the negative of that. 

$l_{32} = -(3/2)$ (since 3/2 was used in the last row operation)\
$l_{31} = 2$ (since -2 was used in the second row operation)\
$l_{21} = -1$ (since 1 was used in the first row operation)

$L = \left[\begin{matrix} 1 & 0 & 0 \\ -1 & 1 & 0 \\ 2 & -(3/2) & 1 \\\end{matrix}\right]$

Check $LU = A$

$\left[\begin{matrix} 1 & 0 & 0 \\ -1 & 1 & 0 \\ 2 & -(3/2) & 1 \\\end{matrix}\right]
* 
\left[\begin{matrix} 1 & 1 & 1 \\ 0 & 2 & 2 \\ 0 & 0 & 2 \\\end{matrix}\right]
= 
\left[\begin{matrix} 1 & 1 & 1 \\ -1 & 1 & 1 \\ 2 & -1 & 1 \\\end{matrix}\right]$ 

Importance - If an $LU$ factorization exists, it makes it efficient to solve any system of the form $Ax=b$ using $LUx = b$. You do this in 2 steps:

1) Solve $Ly = b$ using forward substitution to solve for $y$ ($b$ is known)
2) Solve $Ux = y$ using backward substitution

We're looking for methods that help us solve linear systems more efficiently. These two methods $Ly = b$ and $Ux = y$ solve in $n^2$ which is significantly faster for a large system. The caveat is you need the $LU$ factorization which requires Gaussian elimination which take $n^3$. In some cases, it's easy to get $LU$

In [162]:
import numpy as np

A = [[1,1,1],[-1,1,1],[2,-1,1]]
L = [[1,0,0],[-1,1,0],[2,-(3/2),1]]
U = [[1,1,1],[0,2,2],[0,0,2]]

A_answer = np.dot(L, U)

print(f'A_answer = \n {A_answer}\n')
assert np.array_equal(A, A_answer)

assert np.array_equal(gaussian_elimination(A),U)

def get_L(coefficients):
    
    

A_answer = 
 [[ 1.  1.  1.]
 [-1.  1.  1.]
 [ 2. -1.  1.]]



### Matrix Inverses
Previously, we focused on solving with efficiency in mind. Inverse matrixes are nice algebraic ways to solve matrices. Computationally, it's very expensive. 

Definition: The inverse of a matrix $A \in \mathbb{R}^{m*n}$ (if it exists) is a matrix $B \in \mathbb{R}^{m*n}$ such that $BA$ = $I_n$ = $AB$

$I_n = \left[\begin{matrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \\\end{matrix}\right] \in \mathbb{R}^{m*n}$

If such a $B$ exists, it is unique and it is denoted by $A^{-1}$

To compute $A^{-1}$, row-reduce the augmented matrix $[A | I_n]$ until the left hand square is $I_n$ then the right hand square will be $A^{-1}$ 

Example: 

$A = \left[\begin{matrix} 1 & 2 \\ 3 & 4 \end{matrix}\right]$\
$I_n = \left[\begin{matrix} 1 & 0 \\ 0 & 1 \end{matrix}\right]$

$[A | I_n]$ = $\left[\begin{matrix} 1 & 2 &|&1&0 \\ 3 & 4 &|&0&1 \end{matrix}\right] \rightarrow $

Now we need to row-reduce.
1) $Row_2 \leftarrow Row_2 - 3Row_1$ = $\left[\begin{matrix} 1 & 2 &|&1&0 \\ 0 & -2 &|&-3&1 \end{matrix}\right] $
2) $Row_1 \leftarrow Row_1 + Row_2$ = $\left[\begin{matrix} 1 & 0 &|&-2&1 \\ 0 & -2 &|&-3&1 \end{matrix}\right] $
3) $Row_2 \leftarrow Row_2 -(1/2)Row_2$ = $\left[\begin{matrix} 1 & 0 &|&-2&1 \\ 0 & 1 &|&3/2&-1/2 \end{matrix}\right] $

$A^{-1} = \left[\begin{matrix} -2&1 \\ 3/2&-1/2 \end{matrix}\right] $

Check $AA^{-1} = I_n$

$\left[\begin{matrix} 1 & 2 \\ 3 & 4 \end{matrix}\right]
* 
\left[\begin{matrix} -2&1 \\ 3/2&-1/2 \end{matrix}\right] 
= 
\left[\begin{matrix} 1 & 0 \\ 0 & 1 \end{matrix}\right]$

**Importance:** 
If you know $A^{-1}$ you can solve for $x$ in $Ax = b$ very quickly:

$Ax = b$\
$A^{-1}Ax = A^{-1}b$ (multiply both sides by the $A^{-1})$\
&nbsp;&nbsp;&nbsp;&nbsp;($A^{-1}A$ is just the identity matrix, which if multiplied by $x$, just gives $x$)\
$x = A^{-1}b$ (Shows that multiplying $b$ by $A^{-1}$ gives us $x$)

This seems like the easiest algebraic way to solve linear systems but it's impractical for solving large linear systems because of performance. As a conceptual method, it's a nice way to solve a linear system.

In [82]:
import numpy as np

A = [[1,2],[3,4]]
Ai = [[-2,1],[3/2,-1/2]]
In = [[1,0],[0,1]]

In_answer = np.dot(A, Ai)

print(f'In_answer = \n {In_answer}\n')
assert np.array_equal(In, In_answer)

In_answer = 
 [[1. 0.]
 [0. 1.]]



### Iterative Solution Methods

For large linear systems, direct methods can be too inefficient. Iterative methods give an approximate solution and work by first guessing a solution for $x$, then applying a sequence of operations to improve this guess. The method halts when successive approximations are sufficiently similar. 

Examples:
* Jacobi Method
  1) Guess $x^{(0)}$
  2) Repeat for $k = 1, 2,...$ until convergence\
  For $i=1$ to $n$\
  &nbsp;&nbsp; Set $x_i^{(k+1)} = (b_i - \sum_{j!=i}^na_{ij}x_j^k) / a_{ii}$ (Similar to the formula used in backward substitution. But in backward subtitution, $x_j$ is the true solution but in Jacobi, $x_j$ is an approximation. If using Jacobi, $x_j$ happens to be the true solution, which can happen for some matrices, $x_i^{k+1}$ is also the true solution.)
* Gauss-Seidel Method - Similar to Jacobi method
  1) Guess $x^{(0)}$
  2) Repeat for $k = 1, 2,...$ until convergence\
  For $i=1$ to $n$\
  &nbsp;&nbsp; Set $x_i^{(k+1)} = (b_i - \sum_{j<i}^na_{ij}x_j^{k+1} - \sum_{j>i}^na_{ij}x_j^{k}) / a_{ii}$ (Gauss-Seidel uses previously known values of $x_j^{k+1}$ to converge faster if done sequentially)
* SOR Methods - Successive Over-relaxation Methods - Modification of Gauss-Seidel that uses weights.\
  1) Guess $x^{(0)}$
  2) Repeat for $k = 1, 2,...$ until convergence\
  For $w \in [0,2]$\
  $x_i^{k+1} = (1-w)x_i^k + w((b_i - \sum_{j!=i}^na_{ij}x_j^k) / a_{ii})$\
  * Weighting parameter is a general method for taking an iterative method that's not converging fast enough and speeding it up. A higher $w$ moves you away from the previous solution faster. A lower $w$ will move you towards a new solution more slowly. 
  * These are pretty good practical methods for solving linear systems in a reasonable amount of time. 
  
Comparison:
* Jacobi method can be parallelized (no knowledge of previous values is needed)
* Gauss-Seidel can't be parallelized because you need the value you just computed to compute the next value. If you're updating $x_i^{k+1}$ sequentially, GS converges faster. 

### Recap

High-Level Objectives
* Define linear systems and explain how to represent them
* Solve linear systems using:
  * E.g., Gaussian elimination with backward substitution
  * LU factorization of the coefficient matrix
  * Inverse of the coefficient matrix
  * An iterative method
  
Linear Systems: Expressions
* List of multivariable equations
* Single matrix-vector equation
* Augmented matrix

Linear Systems: Types
* Overconstrained
* Perfectly constrained
* Underconstrained
* Focus is on square systems
  * Underconstrained systems can be made square by adding rows of zeroes.
  * Overconstrained systems can approximate a square system indirectly by solving related square systems.
  
Linear Systems: Solutions
* Direct methods rely on changing the system to a simpler one with the same solution
* E.g., Gaussian elimination with backward substitution
* Gaussian elimination reduces a system to upper triangular form using elementary row operations.
* Backward substitution solves iteratively for $x$ in the order $x_n,...,x_1$.

Elementary Matrices
* Row operations can be performed (or unperformed) by using matrix multiplication.

Linear System Solution: LU Factorization
* If Gaussian elimination doesn't require row swaps, the coefficient matrix has an LU factorization.
  * L: lower triangular matrix
  * U: upper triangular matrix with nonzero diagonals
* If there is an LU factorization for A, solvingAx=b can be done by using forward and backward substitution.
* L and U can be stored as part of the Gaussian elimination algorithm without additional computation.

Linear System Solution: Matrix Inverses
* An inverse of matrix $A$ (if it exists) is a matrix $B$ so that $AB=BA=I$.
* Computed by reducing an augmented matrix $[A|I]$ to the form $[I|B]$.
  * If it works, $B=A^{−1}$
* If $A$ has an inverse, $Ax=b$ has the unique solution $A^{−1}b$.

Linear System Solution: Iterative Methods
* Guess a solution, then perform operations to improve the guess.
* Jacobi Method
* Gauss-Seidel Method
* SOR (Successive Over-relaxation) Method